### PR TITLE
Fix "invalid multibyte escape" error

### PR DESCRIPTION
**Pull request by smitelli**
This fixes the "invalid multibyte escape" error on Ruby 2.0, and updates two of the included PNGs with the latest content from 10.9.3.

### CODE REVIEW

**Comment by LukeLR** [comment]
Haha :D Just seeing that you did the same thing as I did :D

**Comment by smitelli** [comment]
Great minds think alike. :wink:

**Comment by LukeLR** [comment]
Yep :wink:

**Comment by kcparashar** [comment]
@tmm1 Can you merge this request?

**Pull request merged**
